sonar.projectKey=NotesApp
sonar.projectName=Notes App
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.sources=backend/src,frontend/src
sonar.login=sqp_579d4fb0c37c314eef6588bc3318d336bb40e166
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.tests=backend/tests

sonar.test.inclusions=**/*.test.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**

sonar.sourceEncoding=UTF-8
# sonar.token=sqp_579d4fb0c37c314eef6588bc3318d336bb40e166
